# Credentials and endpoints
INFURA_URL: "" # Only necessary for token bots which don't rely on an API
BOT_TOKEN: ""

# Contracts (only necessary when creating a token price bot which uses the LP pool for price retrieval
POOL_CONTRACT: ""
TOKEN_CONTRACT: ""
